package com.mulungushi.api;

import retrofit2.Call;
import retrofit2.http.Body;
import retrofit2.http.GET;
import retrofit2.http.POST;
import retrofit2.http.Path;
import retrofit2.http.Query;

import java.util.List;

import com.mulungushi.api.model.LoginRequest;
import com.mulungushi.api.model.LoginResponse;
import com.mulungushi.api.model.Student;

/**
 * Role 7 - ApiService
 * All API endpoint definitions for the Student Registration & Lab Group app.
 * The actual HTTP logic is generated by Retrofit at runtime.
 */
public interface ApiService {

    // ============================================================
    // AUTHENTICATION
    // ============================================================

    @POST("api/auth/login")
    Call<LoginResponse> login(@Body LoginRequest request);

    // ============================================================
    // STUDENTS
    // ============================================================

    @GET("api/students")
    Call<List<Student>> getStudents(
            @Query("search") String search,
            @Query("programme") String programme,
            @Query("group") String group,
            @Query("status") String status
    );

    @GET("api/students/{id}")
    Call<Student> getStudentById(@Path("id") String studentId);

    // ============================================================
    // HEALTH CHECK
    // ============================================================

    @GET("health")
    Call<Object> healthCheck();
}